#
# Deploy command:
# docker stack deploy -c docker-compose.yml `basename $(pwd -P)`
#
# Copyright (C) 2020 E01-AIO Automação Ltda.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Nelio Santos <nsfilho@icloud.com>
#
version: "3.6"

services:
  mongodb:
    image: mongo:4.4
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
      MONGO_INITDB_DATABASE: "core"
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.54
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    networks:
      - internal

  adminer:
    image: adminer:4.7
    ports:
      - 8082:8080
    links:
      - postgres:postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:12.4
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PORT: 5432
      POSTGRES_DB: "core"
      POSTGRES_PASSWORD: "password"
      PGPASSWORD: "password"
    ports:
      - 5432:5432

  redis:
    image: redis:6
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      REDIS_EXTRA_FLAGS: "--maxmemory 250mb"
    command: >
      --requirepass password
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=password
      - ADDRESS=0.0.0.0
    ports:
      - 8083:8081
    networks:
      - internal

  queue:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  rabbitmq:
  postgres:
  mongodb:
